### ISSUE TITLE
Error: success?

### ISSUE THREAD

**Issue by eatradish** [AOSC-Dev/ananbot#21]
```
(node:30059) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'join' of undefined
    at TelegramBot.telegramBot.on (/home/sakiiily/ananbo/index.ts:23:30)
    at TelegramBot.emit (events.js:198:13)
    at TelegramBot.EventEmitter.emit (domain.js:448:20)
    at TelegramBot.excute (/home/sakiiily/ananbo/telegram/bot.ts:83:21)
    at EventEmitter.client.on (/home/sakiiily/ananbo/telegram/bot.ts:59:33)
    at EventEmitter.emit (/home/sakiiily/ananbo/node_modules/eventemitter3/index.js:181:35)
    at Client._defineProperty [as emit] (/home/sakiiily/ananbo/node_modules/tdl/dist/client.js:177:21)
    at Client._handleUpdate (/home/sakiiily/ananbo/node_modules/tdl/dist/client.js:367:14)
    at Client._handleResponse (/home/sakiiily/ananbo/node_modules/tdl/dist/client.js:347:19)
    at Client._loop (/home/sakiiily/ananbo/node_modules/tdl/dist/client.js:322:34)
(node:30059) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30059) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by eatradish** [comment]
@Garfield550 （

**Comment by eatradish** [comment]
bug at https://github.com/AOSC-Dev/ananbot/blame/master/telegram/bot.ts#L85
